### PR TITLE
add new privileges to existing roles

### PR DESCRIPTION
**Pull request by petrjasek**
SDESK-4668

### CODE REVIEW

**Comment by petrjasek** [comment]
you can update the privileges names later as you need

**Comment by tomaskikutis** [comment]
Thanks. Do upgrade scripts work the same for plugins? I want to move planning/publisher related field out of the core and to respective repositories. Do I simply copy this file and adjust the field names and it will work the same there?

**Comment by petrjasek** [comment]
no that wouldn't work, for now you have to add all those privileges via core

**Comment by tomaskikutis** [comment]
Do you consider this an issue? Should we work on supporting upgrade scripts in extensions/modules?

**Comment by petrjasek** [comment]
I'm not sure, we didn't need it yet and in this case it wouldn't be a problem to have a privilege for a module you don't use

**Pull request merged**
